Repository vapor/queues, pull requests merged in 2020-07, with the labels that each got.

#76 QU-75 added Lifecycle handling for InProcessJobs and scheduledJobs
  Sources/Queues/Application+Queues.swift
  Sources/XCTQueues/TestQueueDriver.swift
  Tests/QueuesTests/QueueTests.swift
Labels: enhancement

#80 Allow starting multiple queues in process
  README.md
  Sources/Queues/Application+Queues.swift
  Sources/Queues/QueuesCommand.swift
  Sources/XCTQueues/TestQueueDriver.swift
  Tests/QueuesTests/QueueTests.swift
Labels: bug, semver-minor

#82 Print log if scheduled job fails
  .gitignore
  Sources/Queues/QueuesCommand.swift
  Tests/QueuesTests/QueueTests.swift
Labels: bug, semver-patch

#83 Logging metadata improvements
  Sources/Queues/Queue.swift
  Sources/Queues/QueueWorker.swift
  Sources/Queues/QueuesCommand.swift
Labels: semver-patch
